// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-CK55B9KUa9d1E3RbM7xcI5TO-52ou4',
    appId: '1:812946540656:web:0e7e47f4705e9fc92a8cb5',
    messagingSenderId: '812946540656',
    projectId: 'lawploy-c677e',
    authDomain: 'lawploy-c677e.firebaseapp.com',
    storageBucket: 'lawploy-c677e.appspot.com',
    measurementId: 'G-WSH6W01NFY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwgfwDXhUoter6zIsgiPt-jnpsH0ulb8E',
    appId: '1:812946540656:android:06e211d97026e5c22a8cb5',
    messagingSenderId: '812946540656',
    projectId: 'lawploy-c677e',
    storageBucket: 'lawploy-c677e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn9zul_Z7fylOStbQ5Ie6axl_vO5QrGes',
    appId: '1:812946540656:ios:ab6f4abae5802c832a8cb5',
    messagingSenderId: '812946540656',
    projectId: 'lawploy-c677e',
    storageBucket: 'lawploy-c677e.appspot.com',
    iosClientId: '812946540656-drahctn4qpa91oehtd33i982o3tvdvl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawployApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn9zul_Z7fylOStbQ5Ie6axl_vO5QrGes',
    appId: '1:812946540656:ios:ab6f4abae5802c832a8cb5',
    messagingSenderId: '812946540656',
    projectId: 'lawploy-c677e',
    storageBucket: 'lawploy-c677e.appspot.com',
    iosClientId: '812946540656-drahctn4qpa91oehtd33i982o3tvdvl3.apps.googleusercontent.com',
    iosBundleId: 'com.example.lawployApp',
  );
}
